version: '2.1'

services:

  distributed-mysql:
    build: ./
    image: distributed-mysql-img
    command: mvn test
    depends_on:
      mysql-node-1:
        condition: service_healthy
      mysql-node-2:
        condition: service_healthy
      mysql-node-3:
        condition: service_healthy

  mysql-node-1:
    image: mysql:8.0
    environment:
      MYSQL_USER: dmysql
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: dmysql_test_db
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 20

  mysql-node-2:
    image: mysql:8.0
    environment:
      MYSQL_USER: dmysql
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: dmysql_test_db
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 20

  mysql-node-3:
    image: mysql:8.0
    environment:
      MYSQL_USER: dmysql
      MYSQL_PASSWORD: test
      MYSQL_DATABASE: dmysql_test_db
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 20