version: '2.1'

services:

  distributed-mysql:
    build: ./
    image: distributed-mysql-img
    container_name: "distributed_mysql"
    ports:
      - "9090:9090"
    depends_on:
      mysql-node-1:
        condition: service_healthy
      mysql-node-2:
        condition: service_healthy
      mysql-node-3:
        condition: service_healthy

  mysql-node-1:
    image: mysql:8.0
    container_name: "mysql_node_1"
    environment:
      MYSQL_USER: dmysql
      MYSQL_PASSWORD: change-me-nf342bfc2
      MYSQL_DATABASE: dmysql_db
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./var/docker/mysql_node_1:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 20

  mysql-node-2:
    image: mysql:8.0
    container_name: "mysql_node_2"
    environment:
      MYSQL_USER: dmysql
      MYSQL_PASSWORD: change-me-nf342bfc2
      MYSQL_DATABASE: dmysql_db
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./var/docker/mysql_node_2:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 20

  mysql-node-3:
    image: mysql:8.0
    container_name: "mysql_node_3"
    environment:
      MYSQL_USER: dmysql
      MYSQL_PASSWORD: change-me-nf342bfc2
      MYSQL_DATABASE: dmysql_db
      MYSQL_RANDOM_ROOT_PASSWORD: 1
    volumes:
      - ./var/docker/mysql_node_3:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin" ,"ping", "-h", "localhost" ]
      timeout: 3s
      retries: 20